steps:
- name: "gcr.io/cloud-builders/docker"
  args:
  - build
  - "--tag=europe-west1-docker.pkg.dev/hcred-vertexai/hcred-vertexai-docker-repo/base:latest"
  - "--file=./Dockerfile.base"
  - .
images:
- "europe-west1-docker.pkg.dev/hcred-vertexai/hcred-vertexai-docker-repo/base:latest"